#!/bin/bash

# bail unless ($1 = eth0)
# dont call exit
if [ "$1" != "eth0" ] ; then
  :
else
  # After a network interface is loaded
  # this updates the /etc/issue file to show the ip address
  # and product name
  FILE="/var/www/miq/vmdb/config/locales/en.yml"
  [[ -a /var/www/miq/vmdb/config/locales/en_productization.yml ]] && FILE="/var/www/miq/vmdb/config/locales/en_productization.yml"

  # extract PRODUCT from en:product:name
  PRODUCT=`sed -n ':a;N;s/\([ ]*product:\n[ ]*name: \)//p' $FILE`
  IP=`hostname -I | cut -d' ' -f1`

  # replace \p with the product name
  # replace \i with the ip address

  sed /etc/issue.template -e "s/\\\\P/${PRODUCT}/g" -e "s/\\\\i/${IP}/g" > /etc/issue
  cp /etc/issue /etc/issue.net
fi
