#!/bin/bash
#
# Description: Sets the environment for scripts and console users
#

# for all properties files
#   set variables from all lines (skipping comments and blank lines)
# see systemd EnvironmentFile for info on the file format
for prop in /etc/default/*.properties ; do
  while read -r line ; do
    if [[ ! $line =~ ^(#|;|$) ]] ; then
      export $line
    fi
  done < $prop
done
