#!/bin/bash
#
# Description: Sets the environment for scripts and console users
#

for prop in /etc/default/*.properties ; do
  if [[ -e ${prop} ]] ; then
    # lines starting with a semi or a # are ignored
    export $(sed -e 's/^[#;].*//g' ${prop} | xargs)
  else
    echo "missing evm properties file: ${prop}"
  fi
done
