#!/bin/bash
# Description: Sets the PostgreSQL environment for scripts and console users
#

export APPLIANCE_PG_CTL=/opt/rh/rh-postgresql95/root/usr/bin/pg_ctl
export APPLIANCE_PG_MOUNT_POINT=/var/opt/rh/rh-postgresql95/lib/pgsql
export APPLIANCE_PG_DATA=${APPLIANCE_PG_MOUNT_POINT}/data
export APPLIANCE_PG_SERVICE=rh-postgresql95-postgresql
export APPLIANCE_PG_SCL_NAME=rh-postgresql95
export APPLIANCE_PG_PACKAGE_NAME=${APPLIANCE_PG_SCL_NAME}-postgresql-server

[[ -s /opt/rh/${APPLIANCE_PG_SCL_NAME}/enable ]] && source /opt/rh/${APPLIANCE_PG_SCL_NAME}/enable
